project:
  type: website
  resources:
    - "docs_pdf/*"

website:
  description: "A blog built with Quarto"
  site-url: https://ce-macroeconomia-internacional.github.io/blog_prueba/ # you must change this appropriately for RSS feeds to work properly
  title: "Blog del Circulo de Macroeconomia en un Entorno Global"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://linkedin.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



